name: Build Python Binary for Termux (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Cross-compile with Nuitka for ARM64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU & Docker for ARM64
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build in ARM64 container
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${{ github.workspace }}:/app \
          ubuntu:22.04 \
          bash -c "
            apt update &&
            DEBIAN_FRONTEND=noninteractive apt install -y python3 python3-pip python3-dev python3-venv build-essential patchelf wget binutils ccache &&
            pip3 install nuitka &&
            cd /app &&
            nuitka --standalone --onefile --static-libpython=yes  bugscan.py
          "

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: termux-binary
        path: bugscan.bin
        
